#!/usr/bin/env bash

instance_id=$1
user=ec2-user

if [[ -z ${instance_id} ]]; then
  echo "Usage: aws ssm ssh instance_id" 1>&2
  exit 1
fi

availability_zone=$(aws ec2 describe-instances \
  --instance-id ${instance_id} \
  --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' \
  --output text
)

tmpfile=$(mktemp /tmp/eic.ssh.XXXXXX)
ssh-keygen -C "tmp key" -q -f ${tmpfile} -t rsa -b 2048 -N ""
public_key=${tmpfile}.pub
private_key=$tmpfile

echo "Sending ssh public key" 1>&2
aws ec2-instance-connect send-ssh-public-key \
  --instance-id ${instance_id} \
  --availability-zone ${availability_zone} \
  --instance-os-user ${user} \
  --ssh-public-key file://${public_key}

ssh -i ${private_key} ${user}@${instance_id}
