#!/usr/bin/env bash

shell=${1:-sh}
container_id=$(command docker container ls | perl -alne 'print unless $. == 1' | fzf --ansi --height 40% | perl -alne 'print $F[0]')
if [[ ! -n $container_id ]]; then
  exit 1
fi
command docker exec -it ${container_id} $shell
