shell = "zsh"

[plugins]

[plugins."zsh-users/zsh-syntax-highlighting"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins."zsh-users/zsh-syntax-highlighting".hooks]
post = """
  ZSH_HIGHLIGHT_STYLES[path]='none'
  ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan,bold'
  ZSH_HIGHLIGHT_STYLES[arg0]='fg=cyan,bold'
"""

[plugins."zsh-users/zsh-completions"]
github = "zsh-users/zsh-completions"

[plugins."zsh-users/zsh-autosuggestions"]
github = "zsh-users/zsh-autosuggestions"

[plugins."olets/zsh-abbr"]
github = "olets/zsh-abbr"
use = ["zsh-abbr.plugin.zsh"]

[plugins."olets/zsh-abbr".hooks]
pre = """
  brew require eza || return 1
"""
post = """
  abbr load -f
"""

# Plugins installed using Homebrew
# NOTE:
# * 以下のコマンドはHomebrewで導入したものを使用する
# * 通常時も使用するコマンドのため参照先を一つにしたい
# FIXME: /opt/homebrew/optを参照したくないのでなんかいい感じにしたい
[plugins.fzf]
local = "/opt/homebrew/opt/fzf"
use = ["shell/key-bindings.zsh"]

[plugins.fzf.hooks]
post = """
  brew require rg ripgrep || return 1
  FZF_DEFAULT_COMMAND='rg --hidden --no-ignore --files'
"""

[plugins.git]
local = "/opt/homebrew/opt/git"
use = ["etc/bash_completion.d/git-prompt.sh"]

[plugins.git.hooks]
post = """
  GIT_PS1_SHOWUPSTREAM=1
  GIT_PS1_SHOWDIRTYSTATE=1
"""

[plugins.asdf]
local = "/opt/homebrew/opt/asdf"
use = ["libexec/asdf.sh"]
