# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins."zsh-users/zsh-syntax-highlighting"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins."zsh-users/zsh-completions"]
github = "zsh-users/zsh-completions"

[plugins."zsh-users/zsh-autosuggestions"]
github = "zsh-users/zsh-autosuggestions"

[plugins."olets/zsh-abbr"]
github = "olets/zsh-abbr"
use = ["zsh-abbr.plugin.zsh"]

[plugins."git/git-prompt"]
remote = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
