shell = "zsh"

[plugins]

[plugins."zsh-users/zsh-syntax-highlighting"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins."zsh-users/zsh-syntax-highlighting".hooks]
post = """
  ZSH_HIGHLIGHT_STYLES[path]='none'
  ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan,bold'
  ZSH_HIGHLIGHT_STYLES[arg0]='fg=cyan,bold'
"""

[plugins."zsh-users/zsh-completions"]
github = "zsh-users/zsh-completions"

[plugins."zsh-users/zsh-autosuggestions"]
github = "zsh-users/zsh-autosuggestions"

[plugins."olets/zsh-abbr"]
github = "olets/zsh-abbr"
use = ["zsh-abbr.plugin.zsh"]

[plugins."olets/zsh-abbr".hooks]
pre = """
  brew_require eza || return 1
"""
post = """
  abbr load -f
"""

# Plugins installed using Homebrew
# XXX: Use brew --prefix to /opt/homebrew
[plugins.fzf]
local = "/opt/homebrew/opt/fzf"
use = ["shell/key-bindings.zsh"]

[plugins.fzf.hooks]
pre = """
  brew_require fzf || return 1
"""
post = """
  brew_require rg ripgrep || return 1
  FZF_DEFAULT_COMMAND='rg --hidden --no-ignore --files'
"""

[plugins.git]
local = "/opt/homebrew/opt/git"
use = ["etc/bash_completion.d/git-prompt.sh"]

[plugins.git.hooks]
pre = """
  brew_require git || return 1
"""
post = """
  GIT_PS1_SHOWUPSTREAM=1
  GIT_PS1_SHOWDIRTYSTATE=1
"""
