# The best colorful flat theme for your favorite editor and terminal emulator.
[[plugins]]
repo = 'raphamorim/lucario'
on_event = ['VimEnter']
hook_add = '''
  syntax on
'''
hook_post_source = '''
  autocmd VimEnter * ++nested colorscheme lucario
'''

# # A light and configurable statusline/tabline plugin for Vim
[[plugins]]
repo = 'itchyny/lightline.vim'
on_event = ['ColorScheme']

# Rainbow Parentheses Improved, shorter code, no level limit, smooth and fast, powerful configuration.
[[plugins]]
repo = 'luochen1990/rainbow'
on_event = ['BufEnter']
hook_source = '''
  let g:rainbow_active = 1
'''

# Auto close parentheses and repeat by dot dot dot...
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['BufEnter']

# This plugin is used for displaying thin vertical lines at each indentation level for code indented with spaces.
[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = ['InsertEnter']
