# The best colorful flat theme for your favorite editor and terminal emulator.
[[plugins]]
repo = 'raphamorim/lucario'
on_event = ['VimEnter']
hook_add = '''
  syntax on
'''
hook_post_source = '''
  autocmd VimEnter * ++nested colorscheme lucario
'''

# # A light and configurable statusline/tabline plugin for Vim
[[plugins]]
repo = 'itchyny/lightline.vim'
on_event = ['ColorScheme']

# Rainbow Parentheses Improved, shorter code, no level limit, smooth and fast, powerful configuration.
[[plugins]]
repo = 'luochen1990/rainbow'
on_event = ['BufEnter']
hook_source = '''
  let g:rainbow_active = 1
'''

# Auto close parentheses and repeat by dot dot dot...
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['BufEnter']

# This plugin is used for displaying thin vertical lines at each indentation level for code indented with spaces.
[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = ['BufEnter']

# fzf is a general-purpose command-line fuzzy finder.
[[plugins]]
repo = 'junegunn/fzf'
on_source = 'fzf.vim'
build = './install --bin'

# Things you can do with fzf and Vim.
[[plugins]]
repo = 'junegunn/fzf.vim'
on_map = ['<Leader>g', '<Leader>f', '<C-]>']
depends = 'fzf'
hook_post_source = '''
  command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
    \ 'rg --line-number --no-heading --color=always --smart-case --hidden --glob=!.git '.shellescape(<q-args>),
    \ 1,
    \ fzf#vim#with_preview({'options': ['--color=16']}, 'right:50%:wrap'),
    \ 0)
  nnoremap <silent><Leader>g :Rg<CR>
  nnoremap <silent><Leader>f :call fzf#vim#files(trim(system('git rev-parse --show-cdup')), fzf#vim#with_preview({'options': ['--color=16']}, 'right:50%:wrap'), 0)<CR>
  nnoremap <silent><C-]> :call fzf#vim#tags(expand('<cword>'))<CR>
'''
