[colors.bright]
black = "#666666"
blue = "#6483fa"
cyan = "#0098b9"
green = "#009e7e"
magenta = "#eb4f9f"
red = "#de692e"
white = "#eaeaea"
yellow = "#809400"

[colors.normal]
black = "#2c2c2c"
blue = "#788bc5"
cyan = "#0c9ab4"
green = "#4d9b7b"
magenta = "#bb789e"
red = "#c07c66"
white = "#d3d3d3"
yellow = "#938f53"

[colors.primary]
background = "#1c1c1c"
