let s:init_dir = expand('~/.config/nvim/init.d/')
exe 'source' expand(s:init_dir . 'dein.vim')
exe 'source' expand(s:init_dir . 'basic.vim')
exe 'source' expand(s:init_dir . 'color.vim')
exe 'source' expand(s:init_dir . 'terminal.vim')
