[General]
  snippetfile = "${HOME}/.config/pet/snippet.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf --height ${FZF_TMUX_HEIGHT:-40%}"
  backend = "gist"
  sortby = "description"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
