[[snippets]]
  description = "benchmark"
  command = "for i in $(seq 1 10); do time zsh -i -c exit; done"

[[snippets]]
  description = "brew"
  command = "brew upgrade; brew cleanup --prune=all -v; brew doctor"

[[snippets]]
  description = "ghq"
  command = "ghq list | grep github.com | perl -pe 's/^[^\\/]+\\///' | xargs -n1 -P10 ghq get -u"

[[snippets]]
  description = "ssh"
  command = "eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa"

[[snippets]]
  description = "dein"
  command = 'nvim --headless -c "try | call dein#update() | finally | qall! | endtry"'

[[snippets]]
  description = "dein"
  command = 'nvim --headless -c "try | call dein#recache_runtimepath() | finally | qall! | endtry"'

[[snippets]]
  description = "submodule"
  command = "git submodule init && git submodule update && git submodule foreach git pull origin master"
